# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docker build pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  docker-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get commit hash
      id: tag_info 
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        CURRENT_DATE=$(date +'%Y%m%d%H%M%S')

        echo "Commit hash : $COMMIT_HASH"
        echo "Current date : $CURRENT_DATE"

        echo "::set-output name=commit_hash::$COMMIT_HASH"
        echo "::set-output name=current_date::$CURRENT_DATE"

    - name: Build and push docker image
      id: build_image
      run: |
        docker build . -t rahkds/basic-restapi-node-task:${{steps.tag_info.outputs.commit_hash}}-${{steps.tag_info.outputs.current_date}}
        echo "${{secrets.DHUB_PASS}}" | docker login -u ${{secrets.DHUB_USER}} --password-stdin
        docker push rahkds/basic-restapi-node-task:${{steps.tag_info.outputs.commit_hash}}-${{steps.tag_info.outputs.current_date}}
