
name: PR integration pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  Run-unit-test:
    name : "Unit Test Cases"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v21.7.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name : Install dependencies
      run : |
        npm ci

    - name: Run tests and collect coverage
      run : |
        npm test -- --coverage
      env:
          CI: true

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage
        
  Snyk-scan:
    name: "Snyk Scan"
    runs-on: ubuntu-latest
    needs: [Run-unit-test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up and run Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        command: code test  

  Sonar-scan:
    name: "Sonarqube static code analysis"  
    runs-on: ubuntu-latest
    needs: [Run-unit-test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4    

    - name: Run SonarQube Scanner
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: 'https://sonarcloud.io'     
      with:
        args:
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}
          -Dsonar.organization=${{ secrets.SONAR_ORG_KEY}}
