
name: PR integration pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v21.7.3]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
