name: Test container integration

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version ro run'
        required: true
        default: '18'

jobs:
  container-test-job:
    name: container test job
    runs-on: ubuntu-latest
    timeout-minutes: 0.02
    container:
      image: node:${{ github.event.inputs.node_version }}
      env:
          NODE_ENV: development   

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name : Install dependencies
      run : |
        npm ci

    - name: Run tests
      run : |
        npm test
      env:
          CI: true   
