name: Test container integration

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version ro run'
        required: true
        default: '18'

jobs:
  container-test-job:
    name: container test job
    runs-on: ubuntu-latest
    timeout-minutes: 1
    container:
      image: node:${{ github.event.inputs.node_version }}
      env:
          NODE_ENV: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name : Install dependencies
      run : |
        npm ci

    - name: Run tests
      run : |
        npm test
      env:
          CI: true

  service-test-job:
    name: service container test job
    runs-on: ubuntu-latest
    timeout-minutes: 1
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379 

    steps:
    - name: Wait for Redis to be ready
      run: |
        echo "Waiting for Redis to be ready..."
        until docker ps --filter "name=redis" --filter "status=running" -q; do
          echo "Waiting for Redis..."
          sleep 1
        done
        docker ps -a
        echo "Redis is ready!"

    - name: Verify Redis connection
      run: |
        docker exec redis redis-cli ping

